name: Test Automation Workflow

on:
  schedule:
    - cron: '00 18 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running Test Automation Framework with Maven
        run: |
          mvn test site -X -Dbrowser=chrome -DsikLambdaTest=true -DIsHeadless=false || echo "Tests failed, continuing to artifact upload"

      - name: Debug - List all files
        run: ls -R

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-logs
          path: target/surefire-reports/

      - name: Upload Test Report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-report
          path: report.html

      - name: Upload TestNG Output Folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-output
          path: test-output/

      - name: Test Execution Status
        run: echo "Test Execution Completed at $(date)"


















      

  
