name: Test Automation Workflow

on:
  schedule:
    - cron: '00 18 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Test Automation Framework with Maven
        run: |
          mvn test -X -Dbrowser=chrome -DsikLambdaTest=true -DIsHeadless=false
        continue-on-error: true  # Ensures workflow proceeds even if tests fail

      - name: Debug Verify Logs and Report File Before Upload
        run: |
          echo "Checking logs directory..."
          ls -R logs/ || echo "Logs directory not found!"
          echo "Checking report.html..."
          ls -l report.html || echo "Report file not found!"

      - name: Ensure Log Directory Exists
        run: |
          mkdir -p logs/

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-report
          path: report.html

      - name: Test Execution Status
        run: echo "Test Execution Completed"




















      

  
